name: image-build
on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/image-build.yaml"
      - "!**.md"

jobs:
  image-build:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: improwised/ghar-image
          tags: |
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=ghar-image
            org.opencontainers.image.base.name=summerwind/actions-runner-dind
            org.opencontainers.image.vendor=improwised
            org.opencontainers.image.authors=pratikbalar
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.description=github actions self hosted runner image
            org.opencontainers.image.version={{version}}
            org.opencontainers.image.source=https://github.com/Improwised/docker-ghar-image

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
